/* vinagre-vala.h generated by valac 0.32.0.53-28fa, the Vala compiler, do not modify */


#ifndef __VINAGRE_VINAGRE_VALA_H__
#define __VINAGRE_VINAGRE_VALA_H__

#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS



gchar* vinagre_dirs_get_user_cache_dir (void);
gchar* vinagre_dirs_get_user_data_dir (void);
gchar* vinagre_dirs_get_package_data_file (const gchar* filename);
gboolean vinagre_utils_parse_boolean (const gchar* str);
void vinagre_utils_set_widget_visible (GtkWidget* widget, gboolean visible);
void vinagre_utils_show_error_dialog (const gchar* title, const gchar* message, GtkWindow* parent);
void vinagre_utils_show_many_errors (const gchar* title, GSList* items, GtkWindow* parent);
gboolean vinagre_utils_create_dir_for_file (const gchar* filename, GError** error);
GtkBuilder* vinagre_utils_get_builder (void);
gboolean vinagre_utils_request_credential (GtkWindow* parent, const gchar* protocol, const gchar* host, const gchar* default_domain, const gchar* default_username, gboolean need_domain, gboolean need_username, gboolean need_password, gint password_limit, gchar** domain, gchar** username, gchar** password, gboolean* save_in_keyring);
void vinagre_utils_show_help (GtkWindow* window, const gchar* page);
void vinagre_utils_show_help_about (GtkWindow* parent);


G_END_DECLS

#endif
